<a href="https://colab.research.google.com/github/geekevgin/-Python/blob/main/Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
#task 1
a = np.array([[1, 2, 3, 3, 1],
            [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [3]:
b = a.T
b

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [ ]:
b.shape

In [4]:
mean_a = np.mean(b, axis = 0)
mean_a

array([2. , 8.4])

In [5]:
#task 2
a_centered = a.T - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [7]:
#task 3

d = a_centered[:, [0]]
d

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [8]:
c = a_centered[:, [1]]
c

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [9]:
a_centered_sp = np.dot(d,c.T)
a_centered_sp

array([[ 2.4,  0.4, -2.6, -1.6,  1.4],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4],
       [-2.4, -0.4,  2.6,  1.6, -1.4],
       [ 2.4,  0.4, -2.6, -1.6,  1.4]])

In [10]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
print(a_centered_sp)

8.0


In [11]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

In [12]:
#task 4
np.cov(a)[0, 1]

2.0

In [13]:
#Pandas, task 1
import pandas as pd
authors = pd.DataFrame({'author_id':[1, 2, 3],
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, columns = ['author_id','author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [14]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title' : ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]}, columns = ['author_id','book_title','price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [15]:
#task 2
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [16]:
#task 3
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [ ]:
#task 4
authors_stat = authors_price.groupby('author_name').agg({'price': ['min', 'max', 'mean']})
authors_stat

In [17]:
#task 5
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price.head(2)

author_id author_name   book_title  price    cover
0          1    Тургенев  Отцы и дети    450  твердая
1          1    Тургенев        Рудин    300   мягкая

In [18]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      NaN
Тургенев      650.0    450.0
Чехов           NaN    950.0

In [19]:
book_info.fillna(0)

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [20]:
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
book_info.equals(book_info2)

True